---
language: ruby
rvm:
- 1.9.3
before_script:
- git remote set-url origin $REPO.git
- echo -n $id_rsa_{00..32} >> ~/.ssh/id_rsa_base64
- base64 --decode --ignore-garbage ~/.ssh/id_rsa_base64 > ~/.ssh/id_rsa
- chmod 600 ~/.ssh/id_rsa
- echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- rake setup_github_pages[$REPO]
script:
- bundle exec rake generate
- bundle exec rake deploy
env:
  global:
  - REPO="git@github.com:phatograph/blog"
  - secure: ! 'Sge5rCthtw0QGTfqVGvkVMVP/4RQwwnjM0YYnxeTmImi4cwWQkXDXSuctkKz

      FoGzyvzB75Zbu86Yf9yD5M+2QOdYru4DZdq/d17AEnwFnB+ETjxRcnSbzJaK

      IsmDuWSByshsa0MmB+YnrzhXxzn+Pltz6ZIOsFI6TfGmVOReS4Q='
  - secure: ! 'Dsx1hDK/rHQ+jC3T+PbgUIbLJ28NVicYfLfLFW3QhEhrCGm+4w4TURX2i6nT

      RJYliERzE2JVeQxhpqdO8hPBe+T+3psHbFfJTyC/ATcy+gJCAhURDG3uOgpZ

      xqMbPclNPTmwRwQShF+53eCA4HoIw8ozy6X9ExrAbXTVk2F8sAE='
  - secure: ! 'lhtJOI432Ta3rvOwVP8yJQeMmEqCutCTIdX5m4BvrtMRVRaUNHJmc6aludal

      rt7RTxcGMXnwHyMstjz+3tkkyUD8QcmBMa8BC5V3sL/xsxMaJgpfMNM3B1h4

      TGxJRoMu6U8d2rpITdszRrTN7b6U65dSqG5jmLpYuPtc0bsPr3Q='
  - secure: ! 'ZXaUyXuH7+qkMTjKrR8EYCydAdfNtd19fQ9H4sjMe5j0V3K6zeqlY+j16nrv

      16Gy4HdNwN5b3IoaiuK5gYRJI6b+Oat/7ixXYhy8y/CNOSYr6WEQ6jx42yFq

      rKhQMBNM38jV8GanlO5Yz0On5tF96VL2taRvrVeey8UaVwjqZR4='
  - secure: ! 'IiTqTyyi0fRyCPSVBvJI/iSMn/THtYM7CrRYEu4YHkRMFH9IY0iPYV6Wj3Iy

      EPS5EGD3rifvmU1GSNRTt6VVOE7sjYa/IbCm2kM4oErdg2KzFWGtDeg3Ob77

      8zWwyCc5f+Cx/Wtxdw9wgVE7TtUU2IJc2m3nYlFTKBYkWP2vBP0='
  - secure: ! 'QGbNYyx8Oy9ZxoyiYEsLGMCbAAbSqWcIZprKAhc5XB9PXutQK4YEYuPRKApi

      DlZOF5VOzrCWg/+fqSCgAjS3PkaYPsqkJonizZ9WquHlNvKxssUjOJzFgZ/c

      puusPWM7MjCA8FmwE44z/8oAshWbvajlqoOKEGMqCGumL31XIcE='
  - secure: ! 'GVjPOaZmcb0UKIDUnoNZm+wm377FEa656rFAPgJQXnL04aNLYUUgfGruR0oO

      ilACtvb3K8L8/+IT8gGBt/r7wd76LCV2HxxwNEiu3pE4Eg++xqdFXV+5qCRg

      i0W6nhY2xXXXsfl0SUNWKbXv6egcuV9I+/tt+3TwuA/aepryR3Q='
  - secure: ! 'DNBNLeJN90v0UdcIdAgCVMbmsHbjjGATfnzrPwkhWX6RyZhUx0KAgv/0g0oZ

      cG5wGgITurRa+hkN4EeEBqEBZNrXuJKN7PglKhnKV4OQ89afF13uzNmJ9BH9

      SdI+TFArZVD0464WXBeToLUK9W7zCcObygMniQhlObQp76Z0vC8='
  - secure: ! 'FeRlXUf9Ae1KmMlQfqiGT2G4Qihc4mkxPJgYzZXT4oIpbnanmeJx/V6xrny2

      XWuvc90L0FGH1pX/EHD4XZYy3DxBgfEiQEs/NUQ87i2C5pTveoCWtM953qG7

      jnLCbzMcchKEPe9CWILRNQgdO8Ih7ADlzY+dUELzFl5ZTfJeY9s='
  - secure: ! 'efIQ6O5ErXRkCp5eyut5x/WNU0+RPHUz1H6hFg5qLzl+mUfGvciZVZmcKEWj

      m2MQKZNeRFTriOI0MlfmDlW1fq+xH6QOqhCjMtgZNAvNWZWjb4IdmrPyilgz

      Z3eBu1MzsqN2n5qrLJUBdPaRNPnGSzrlqbmoSEzLy9PsG+qJgio='
  - secure: ! 'KXRrcWS8EwEujdY00UlxAw6+PmUYhX60glf7cqPhg24oliMU4JRGmCCScYIZ

      lL3ZXG73SoXP6PHB1dP0Vwj7Ag7p5B4XpwjIuRFp2q8HPOBJVzLQClwq0KE+

      a6G+l/RXAct6lIOtXvTa7FMouB3thdQbY1A6fQZmG4FbpWLEFHY='
  - secure: ! 'nIfcQ3YUQn9aS9HljzgWDxrdhAR7ZVul57KI7OyEWzNFvAfKtJXFSyVK94CT

      cYgIDsXv4VxQLPRFkJxfvxXkuv/b3HXKrKVjvIxFSk52GR6VLrmnTxww21FI

      faEnfS3c9DBaU3iRCc+APcbyoSpV5jA2IoY+9CJ5E8LCuVUb/40='
  - secure: ! 'SyN+QpYaWjaBVI0uh4RVwnENqtUxD509+7BJk69PM+zKe+qvDJ0vZFDTH1BI

      FQTX7M75d6YsFno2m/ZZa+ux8mHM7yXJY3VVmteMiP+LnFW/Cy7xZEoY8FNE

      66axFXy+6cR1mYCINLvhxPw65Y4wX/fSqcxqHDAI/44AOAMALx4='
  - secure: ! 'fp1+cwFyDKGMVlyxPZekQCQYCqc7TFBFCPIggaaXRRH+d/JYO50PBGEAACdu

      RlI3+v9CRYBT4pgMLF8hJiVQlv/1yxq2QNX1gdJh/M3zaERZa1D0q7yp6qVq

      aN9+Ou8haz6uSG5szhsPZlCg5TnMHGfRH89GzJO6cdMvHBlgMnU='
  - secure: ! 'GHqyl+11OInc7S99YlwpFiDgc8AerRbHc0pLS33kjzLv8oSKY7L68JK6taXS

      voVbPAN5tRfkx6166gPkZIzuSQmS7LT9Py2YWbT7+VKnurC+SDomC7IyaHq/

      ZaqqwF8h16rtzimumdBqVaPVYvGgC5a3psUkBZIizzl6nOIYBPo='
  - secure: ! 'HK15PAVpQ75kAT7CPJ+9KMwYsQBDZkf6YY+vFm/5SHgJ/50W1FVU+Ju5d0ya

      A+5C7l+zwpAHjiO6ZmGBTHCmSuLOgqXyDcAsa3t1is0F31TuOQCgf57Z+tPa

      UmgB/4CNs328iW1ryDWdEtzUYQz8KsV8iWTxX6SZqTbf4qxxHPY='
  - secure: ! 'eRHzioj8HRCCGEy7BkWgfi+K3IZUfjLxa+CuO7GyxIdv6IoAB9NMUDsWoRDD

      fa1bR9J3IdFS0MKGROOBI7ESmEpPVC7qOgIIsPwpT6nJcy0Na8x4cGfvR8YZ

      RZxSZoNUxlVh6L0o7S2jiEX6QVEVRpIXCdzq4vPDhsv3zPnicV0='
  - secure: ! 'VStGhV7bTD5D4HNIfrEzEueOR6nQzPf6A1JfddSnXR/7KFxFPTFAdOCe5Bb6

      3hhhL7L69Bj7Bs4xBCsngrwBm0R9RwkatGv7rMBuAH1xZLK0CFX0Hfmjt7Oo

      NQDm994BTEiQCKCDQ1tErIBiGAazxYVh8yoDa7lb3WUJFGqc4tY='
  - secure: ! 'dQOuEAjh2bBHpF6h3V+CEdmV8SbqyrZdBpMToXSsos0aWQeG14D2OzsXCC5A

      bnXJYzATJtLzeU8VFgayPMuRj9HiHbrpTdNXtwIGd2GiXlMt1Rq2fwFog+Ti

      6BxCuPfxonxQkP3uE+8uBwFpBMUlU9FzImWM1KoIW2AlWWdg14w='
  - secure: ! 'kCa5AjUVeNZ5x072PVxkFP4vmOdUZSvdQZzURkWlHRwKLADiYqikGe6kXb/L

      P+MBi+uueffThHjkNDx8ii7cVvTAPzouLsP6VVzt8l4XCl/azIlsxzG2pfQs

      54u5tzohhgj0/qEDty94alizE91V7WNRJBlLCr3vhonUjJeOJ9o='
  - secure: ! 'Ns6MuMYAistaUB809PUvS8xtozm59nfT79PhX02EWdNENl43btxZvKA0IvCM

      +Vns22wpKlZg6xdtiF1PayP0vumX8EkC5/7xK74Amd6Vlii44v2slVbf977S

      XmHeaeAscRXnAXzpBedSJAQ+Nd82X5WaZHpAbU69ddMTMJlvbLw='
  - secure: ! 'YCSIFp1jWNPELKTRpg5/+85DjyStSIVRJvlRdPaaCeQmescpYzSWQxUOESrU

      AYRzXVOc4DZnbUjBP2h0wYohUD0VaV2EcafrxnWzxEaWUroJX1ryyOAwl5ok

      ijP3icVwUT/NbXhjWaYXDEu3pMAwlCVC/iPs9LT9WHNbEma7JLQ='
  - secure: ! 'YV40bnszGUu0hF1n6dMjj9iA1wLJH+o2HYSv/CltgtWmoVKeWJaChIuwnFiI

      EzRDdhWMlhmMopE7TITx7FAdoEesmH8g3zC3UG9YW1xZkn7jceamyAVZiZcP

      QWz9tjs7+zYH8m1riwCofkotsTRvy4w6At8JkT/d2+R/znFcbjI='
  - secure: ! 'VtGc2+YkBHMKUox1hfWf9/8TXVy3jWoZ4QGqYoVm1K7mEn4R8kdE+VSmIpTF

      TeePNER1fwFD+AfnkyNnIqbowW4nnaAR9UQSHf7ifQ39+B1Jm12mapMTnwPR

      KinCDKey6uarjrWPjytyg778eO+IgSfBimQIHTtMTWH8EQmpKwU='
  - secure: ! 'jtJAvKfdfbD01v3dD0WqFabLbX5brQi5FAn58BejV5ASf9g2pf/JV645mfe4

      z0zbIDjmC3gS6qwpgFvNjc44BJ2Sec2RK8JYbqHJGTzGRdZvPlFx4RQCm2MP

      qM3s/35UEFK64Yj6qEPqzxV2UZjOvrcKHMPknmYnFcl6RYLYX3I='
  - secure: ! 'ijCSEB3HrBHaW1pi8HMg92CQU5ftSzTSw0u7oe4OpkXlRnn1i2llsN7XJM60

      ISENoecBlGrCqHoOcoyOuQD1E36K7+u8oKL3NEZccwAakOCP4UQBOPc6JZGn

      K1QbkMfI2gCI6jqjnKv33fK1ZYZ8bmZTKmzg9xdygaqW3gDTR50='
  - secure: ! 'Ldg64iHZNidyb3hXTIJp73FDKnn4ZY4ZKuyJueoz1rZeFr+P17rDTaIJkLHc

      ivRANdBszcK/3xbPi0wWXFU3/uunVTxLoyygMBIWkGSjFt9xz9ps0LW8XOKW

      i9mEgYz8FGK2u9dVutNR63HvdqkvqOdt/FxH5nxKsN2KEcOe43A='
  - secure: ! 'i/CMp3sBX5NMjkeDyqmDyJLYSH8jo1UeyFBKDUAGbbVrrNQr7UXBWu4RXZ7j

      MBQfKxZLNM9UZHF7cPm6udoErjlJFN/GdsZZeFtxBO1oAleBx/lm68ISliBa

      TxHPozJUAu+bWt1skOCDdnKM9jjzApNqyRiXXFY3p41HrfyyXgk='
  - secure: ! 'rEpgS3xFWXrqp7Rgp1lW8W2HGjmOmntOlNqWJk+06MTwEtv6AIDfDW5tJBge

      jhT5a7to+uEOxEzWhPrSfx8AjOePhaXuXqYOpw0txXMoilTFMvtHolJ2A8xj

      5aR/NHrE00+sNbQ/EIpvHONzALM3LwLLxoC/i2OSzT+F4eZWdXY='
  - secure: ! 'rlMwDbD/fVjTdDMEvD3BWweW34DYAzSqJbnK/Gl6v+RAl3L0RJ3PIeDybOYr

      z2eGiNdvaBsY2ZIFRDTOSi/i/Iiy3p/0WbWivdiB1jBJj5++HcavTShSS1KK

      aFfIaVXZS74y5l89neIwIk96UR80IZ4XDf9QjdZb50pr91/kZPI='
  - secure: ! 'iXXNvPCFV9vegwUlDUzcS+2kNQMRLwwJ0f3mtHUooqgaMk0/YFzALu3FKFDp

      q4cyjnMsrRi+Fz6BLNaXUzYrgDa8OlbdaNOpIzkLIgpSZODNyt1FRCLTuMsX

      QMpDKiLj7vQ3wc+D7xkpEXJPg7UVrroFXxtjU8GN2I+MekPulqQ='
  - secure: ! 'C9X6+LPJlNPZdC+sP26cJHK39/W6PcWTEFxKJIgRQ/F0ZIGaWwvWWz5U9v1t

      ngWk+KLPNFu5qPBcLrOrv+tBBN6ep8MBHlSU/yNDYMZ5+p6rm2YyqvR1cz18

      NJEZzuP1MOgezhl6dHIFE1ZNJthvTKrHIh6+l/VhlkwuBCj7dyI='
