---
language: ruby
rvm:
- 1.9.3
before_script:
- git remote set-url origin $REPO.git
- git config --global user.email "phatograph@gmail.com"
- git config --global user.name "Phat Wangrungarun (via TravisCI)"
- echo -n $id_rsa_{00..32} >> ~/.ssh/id_rsa_base64
- base64 --decode --ignore-garbage ~/.ssh/id_rsa_base64 > ~/.ssh/id_rsa
- chmod 600 ~/.ssh/id_rsa
- echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- rake setup_github_pages[$REPO]
script:
- bundle exec rake generate
- bundle exec rake deploy
env:
  global:
  - REPO="git@github.com:phatograph/blog-octopress"
  - secure: ! 'Mw6Y4io01wX/f+JpV4AvpQ8Ei4KFuwZEKxPhpB9TrHgYKWDMZGcs5S7FmzN7

      AKzqKkk7Q1aVnKUk77826LO7dU2fEakvnwPgQ7gZJPhYM563YJmVEUK6z8LL

      C/xIHyCZVczjymPBxVRRO7XX7glnXDryHMDEYQGG/vhasi/CWFE='
  - secure: ! 'CntAoeqOPaXC4b3WJ/qGUglwyoutkFDmvharfxbz5TbBxQReHOkkWcicOLBq

      EZwi/uYufcwg72japICRKQBK4RMjEAm8xyKsrZxvYsawSdOAR3HnKlffohLf

      fHpo5T3AQaNTHvBZDAPmJXjiWQAVsqrgWObiPSPRZruPEgARgU8='
  - secure: ! 'ZFaaNLQwxX4geTTOcTwg3HA8AvteiPHPW92QDimcabuoB+ovE87iEc4d1Z5Y

      VkcK4PbC7VIHJ7BffSb0YwItdGxR6iL+nQ6ryGkK+1FFJfMnZ/5Ss7OP4hV8

      56WB1DBAtoqGba0op7JczLRMO5Wgu616F0nC5DCPruN4YMYcamU='
  - secure: ! 'ln3h2pmIslaSdq/2Nv6NryWwF1csPUwC6sdmHwy7k7pM6UeTkGP2LqsHs/YF

      +4I+nq9/HD1ZVY8CKaJkA6y+9wziuSML3ZVgjRuNB/arjT6QvOXgSyi0hnv8

      NS44x6X2KhCQrMEhZJLFVs0cmCmKX7Hfbtd83tVDtZnsXrdyHNg='
  - secure: ! 'uZrbAVZJ+5Gn7k2khKfxqd3UDkKg9p9fjtmSxq0ns4cXY4MECfHjn1ZiBHHG

      JwyMp8ZSxVbbiaBWfC8i2b1JjAHWQEA1+MAi6x9z/Js7b0lkDy8ktchHOEsr

      m7d78KbOry57qzxxCI27rWiKJwrOEbZDI+mPlpUqfqzaBt7YP+c='
  - secure: ! 'O8qRplu2+whSGWVC50kbOqZU/tjjEyTsvkNMCEaiAnfNmpwu6Uzq+T78/kHL

      z/K7BbmO20qfBitrQ7f0r44TheMEIMtBgSr/JtX8f1SPgY+I5CIPMYyJxS5s

      R7uj75YuGJAWqDSYhif3OT9gYj8GYwIWLY+xxdnVgYYd+AE4aEs='
  - secure: ! 'nDKTpgnhMRwPXoMGvqBhi43Rj8kMC3Jg2G4AwxugAEM5WfMWRlqxnqAJm/+O

      O+M0b6Hdx0T1/gha8NEJ3vE9ehk7lwvKmXVdryPXdzNsnOG7vdJ7A37TiHB6

      /9nHM33Z8xwEXYzCdggBQv8TS4IAJ/eszJAPV6buk9IU18XYdgU='
  - secure: ! 'wryUyzTvCZZiuc268lHwF2azeCat1HKyF6vxVmQ2n8vjAoHsFWYo2lxXimd5

      XeVpjimPlGuW9Fr7HYeO+VVgU35yhfylUoM1rqOOAnP4OEyOuBwbSjkUVTuC

      o3V2pe60PhZSJZJ/og917thhhYtbZG3lvrDLZ21q1rnZYDua84Y='
  - secure: ! 'fiUZEwewDyzDMp7H2YveA0xtpZNcMKRZqOLhLlIhE8zKBZKt/S7nIXyjNeVd

      2cQxMmjikcc7JQRoQ7lYo04bNevByZwnYnxsH4BcR0tDLf53PQchkYIGEiPv

      TVOdXvzvi1mkxf8LvzzgggvRmw06vnz5FTZpk865LCkqkyhf1KU='
  - secure: ! 'N6ZriczF+onDQjxhSydTqMVvg+IXuQVYu1E3GgXxf1zfcsByPX75YTGrLgQL

      dr7meGPa7UckFjBKixn0BnfrS/gNhkYtPWPu7mwr5k6EnHAYeZoz29Cc6TYM

      fLtxvKmsOAPYLjlD3rlBWHKUZVPLbO2UdjfunjhjyLAqOgzR540='
  - secure: ! 'nmu/qQm7Hbg6kLjlVdCzqxzH//xW3JUallE+chtzS8n1z/lBZdMJI+tNa3gu

      Z/qlvCvuxxZqs1IT7kCB7oUdO1bgj2NMz+Lyf1siOd+IIgE8Z/EuMlvLIGhH

      QpjoMsSVC1rKXa0t2Kn5Wo1ebwqVm3lM0op1BT7ytKwm9ckBBbE='
  - secure: ! 'b7KHx9JKfHluMTVaqXWOgDuzhbDiBiF/qLvstwFqkbuchFtgY3wdauxFmVOO

      zGGOW3kVi9lks9XHeAdHc9g7rSTGKVXX4yfA76oyvejgEXpdf6bzwumXwD5+

      nFjDFTfnYnDtmy91Sw+eHMnZ+OfcZ40bP15+EhSJLwc+/yhH6UA='
  - secure: ! 'Vif/dHAXXEzBMdL/9Nx9boKYe2/nl6gDsFuLU79ia8wA3Um2l+D6h+O/rgpQ

      ehSv1YyiOuJCznGuD4ktXXi7D41SR3BmKTcT0stmUVKmHWWO7qtLrWAGMpVb

      /vDCMXKicAYF8sj4vng1SSOBiL2a1XrKmy8BwPo88M72T/LaF5I='
  - secure: ! 'BWUdUipe+yO4OmYJj8DsfnldSbSxgxmMNbO4CMYsfJHMlyrQY5vzX8pMxABu

      wbJMiZppWk4OpSmbubrRXvGU66Rexm5pf8aPH0hcJz9+RdgDSTMzc2IiBLwo

      ePXo12JkLAeDWCsGlJ/gCvsWMPfLicZ8hxX38YvcFvQPNidQL2s='
  - secure: ! 'c5TDMwAq5sEn2iMeemwdNBtCdq3fnIZ2MTo3Klq5Y5Aqujoex+peR7C3rsFr

      E7ZkdAEZo7cadJnBcsVGZy7ewHziz9nh96oc6tZDj7U6FMnNjWcVDVxsoJtD

      W00sz/uRSaObxeuryCI1U+Juu/ZvWSFXYhW51i32APUeljuU9AA='
  - secure: ! 'iUmzvJ5SmJWXeJ3bRAsBe/aJ1k5OPmE4CkY7LUJ6/ufVM8H3rJ8U9Qcr/b5a

      rBCI4iGPeIrCfS1imCzF03LBwHMn/mAvPYk9a2g2jHTj+PYFaCQDkdxYMGU4

      cCzdeo8jDRk4dSO3/5duSi+stHmB9xHi4wLamVVP/UpceL39/to='
  - secure: ! 'Y2WbhwhHjqmuTgb6LeCz5/G4S14unxSXYBBx5c8EhDBxnsXWRa57Nctd6Wqd

      NqdVhFTSPtKauDv5pS346RetYhmBa94zBlV7c015/mXd2H+rMMEDYhHhTYQ5

      lSnJBuiw+Yw57UX/DswcpVOcOY58KDZQLvBU5cVWtpJK54veRU4='
  - secure: ! 'U4AkxR3ZeoNWiqXJIrnqfjkmmMCbVpx4Ury2E1aIWf2XixYFcGEAMG6lOQIg

      nt3qpt9Q10S1lwgua32guZ/ms1MfztzLAAnjrNIYyo5INas1FIm6kTpZPod2

      pu+09MTXKIvRW6ZSNITB2W78tbFPYH8SCJ7zrud/mYiUbKEPL8o='
  - secure: ! 'oSzPjpWofdcW8M/UgeZX8LJXhrtghR3VMaY8EdsAqyqtTiFRGAeFnz3yDl+v

      bDCSlgQ5jTjOcrVfpUMZmcgHAmApWKWpHOaS4HKDRTsz2oCywnVfWStmHn3d

      scqIMQTjp1AEVq1TbrUelLHg7ui6d581M27iH7P62HFvTJ726YM='
  - secure: ! 'iJyNrKsWcOAvGsyRW0zz4FXgRYix8rPNSsq8Sqv2wHuACuYkp6N9fVtfp/Zg

      YZq9haY/HvqxoPAPws9p322lNoXM4NYFTdDCpZo7WV48ilvtnsxnksRohdJf

      FNURX11DKy/pIOM6O/rdxLM9m9uw3p428XGR3Ff+EZ1PAoTTyiU='
  - secure: ! 'h8m2+8jRiv2YLyGlum+0FRfKm/tsVJpNIKbGx8Hik/TZZrYKh2J8pArMen+k

      tgP7EOSGTimPIcPUbYhhs6P85x5tFxu3F+AitgynnK+7mfx7XO6RxmdEg1uL

      J6tpJ7dXXq7V8s39+Q7TcsSohUqBG9ZXDVpaX9gk1Ju+3zgBmoQ='
  - secure: ! 'Wos8t7FlURO90rMbTt/jYFqsiFMou9/IsDqUFPliWWOCPlCQ7Gv0PdwaYJG0

      BgezwE9JU/QPRQEwx8hvxeeqyT9qGQ8fYpcNOj2O4Xsbd4L4rZswCN2+fGEo

      IBzm9/LTsYjmvJVlbHwwk/wfcB+Pg9kDmoRgQNeBvxWBmf1e2IA='
  - secure: ! 'IZGYHhl5nM0FiGthTtbKtIs24ImHzvIVtWhIGtTtv2SKkjIZqwtdAvlP7JFs

      wmaYqfzwbAweAX43Qte4h8XHkc0hXyjekADWjcjk5gn0KBkCyBWuPWqhjIhe

      lsLNZq7ofatFpRBmPKml5+A9+odiLBZ8xvC1H5ETPpbyQb5JYiY='
  - secure: ! 'nMjhkSMiCxNQWXPRcGBLJMu57iriESP6ym06hNloQ3VOP6+LmIZ6mk2vNFOn

      Bea8qiThzxWmHt/1pBoy92Ls+tSG/tnALh6sBe9xa2RrGTXxTI0oc5jHaYqG

      c2OD1O/O+Nsh1N+wyf60pZTBvtT8XhdpzNnA24ImO/VecEytq0Y='
  - secure: ! 'M3LA/iFlPSD3o6WRU/AFWCA6Z0A7wXHrHLabnLiPS/j+9UXpf/BEmKL+W74K

      iYHG3CKZgXz+bLwqVkg4693G8aq+HaA15DHpcCV60FYSlA1fn+T371cGaA9i

      AZpO/gt6CkKBtzh0heEKIFkOvhzYLFpYnIsM1QR6zk2cvp/E2ng='
  - secure: ! 'k3E49Rojru/yUjqzfuW7TVJseNiYTfqjt80xCo+pu4/yW80Ckju/B3H30Hxr

      /R+ecvgrIAnZ+t85LIHGA1SH6Wv07FIDTc5UHoDqTbHdsf8XOpmWZiCduJpq

      lfrBMUEKhcXPq3lzTr5ZnN8uFF1rFVMB56lBDQNwikl8DsNc5io='
  - secure: ! 'VYf89erBJtQwkaz9jc13Y7Xh4sDCkKCRrl3176hxNeRNpwHlS//0gKAcOrgK

      Jh8WLZ71EoBnloQm3UALpuSbt0pCMAtznKRF9LAniJBBXtaY75CYSyslRBg/

      MpqMyktYRID9Xq2PGPaX7Gu1Kvtdc3hEJPdKvGt/ap599tDyzDo='
  - secure: ! 'Gs8pcmVvwQnOJOoNKxb4Bq64Q83i+OKtDMbvxa4lXsdgcbQUWiRLCixdj5BI

      YYMHjQyWEeWeM5kCCeP7cj/Q1tfFq68ZKrkkU9R3JA9WqkbACNw/2iR4jd7Q

      yXtUUHSGobzjuLLn+DpdxEm3pTr0P1snYkyvC/J34zqt61b80mQ='
  - secure: ! 'DmdvmYB8kk7t+/9SoywPZdua7a9MzXxuhLOjP5hn4rVJg/iA6iXhZhnwol+J

      4Gkj21d9BvHSo5KBgB6Y04KsxdaX3uFHCotuA89vzyYfpNNFeKadDf70v+uW

      KlruSqCmhk2H55eGkQ4SFPr/8ashpQszP53LZxjf+XJnCGk6Qvo='
  - secure: ! 'CBz2sGmiFqdMZ9ScyrSutlVZpsw20ckL3/khZBz5s9qTObQxWnlxD8DVKopD

      s6V+5DBOPEsLwIS7iB6z0q1qP7JfMCnrbD0sHc0Y1WdEIW8Q1tcabpbKVYXL

      pT1C8qwWeMdJziPqNzeaVb6wrrLuv0mE8ywkNSqNp9bxVQEfZVs='
  - secure: ! 'UkVjSEDFQrtzsf+8npJs+6TpsPISEoGW+2pgt1M4Innykod75Vue5VZGiff9

      DrzZRnPGO7nd92JtIW7d//3zl7eUiineJa6hMIA6dcEkLLVgQC0zkplK5PkD

      +x3gRpg9CJ6UcOrLPrc9JVKYMA40PQxJUYQ6fjycHjmCYQbv2Dc='
  - secure: ! 'kLxCiJZGQj7G6eEuP64SveAg/VlTD2kPAJW91GFJ3IdXA8PxGPON3kKThX8E

      wSwyqoaHJ1gmFKhRJBYwCueGmAOtHSsLDJJtBrWeZ4EV+PQ45E+B43RsdwBK

      2wiqmvmWBbn8ZPboxj5Ba7l2VCJC4eGQ0E5eNJak+G38Zk0zqF8='
